version: "3.9"

services:
  codeproject-ai-server:
    image: codeproject/ai-server:gpu
    container_name: codeproject-ai-server-gpu
    hostname: codeproject-ai-server
    # working_dir: /app
    restart: unless-stopped
    ports:
      - "32168:32168"
    environment:
      - TZ=America/Toronto
    volumes:
      - 'C:\ProgramData\CodeProject\AI\docker\modules:/app/modules'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    # command:
    #  - --Modules:BackgroundRemover:Activate=False
    #  - --Modules:BackgroundRemoval:Activate=False
    #  - --Modules:CustomDetection:Activate=False
    #  - --Modules:CustomObjectDetection:Activate=False
    #  - --Modules:PortraitFilter:Activate=False
    #  - --Modules:SceneClassification:Activate=False
    #  - --Modules:VisionObjectDetection:Activate=False
    #  - --Modules:FaceProcessing:EnvironmentVariables:USE_CUDA=True

# If you wish to use volumes, then:
#    volumes:
#      - codeproject_ai_data:/etc/codeproject/ai
#      - codeproject_ai_modules:/app/modules
#
#volumes:
#  codeproject_ai_data:
#  codeproject_ai_modules: